package:
  name: roq-samples
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') }}

source:
  path: ..

build:
  skip: True  # [win]
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_DESCRIBE_HASH', '00000000') }}_{{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - roq-api
    - roq-oss-benchmark
    - roq-oss-rapidjson
  run:
    - roq-api
    - roq-oss-benchmark
    - roq-oss-rapidjson

about:
  home: https://github.com/roq-trading
  dev_url: https://github.com/roq-trading
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://opensource.org/licenses/BSD-3-Clause
  summary: How to use the trading API.
  description: How to use the trading API.
